import type { Metadata } from "next";
import "./globals.css";
import { Archivo, Inter, Prompt, Public_Sans } from "next/font/google";
import RefProvider from "@/contexts/RefProvider";

const archivo = Archivo({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "600", "700"],
});

const prompt = Prompt({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "600", "700"],
});

const inter = Inter({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "600", "700"],
});

const public_Sans = Public_Sans({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${archivo.className} ${public_Sans.className} ${inter.className} ${prompt.className}`}
            >
                <RefProvider>{children}</RefProvider>
            </body>
        </html>
    );
}
